
services:
  db:
    image: mysql:latest
    volumes:
      - bluepi_db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bluepi
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - db-networks

  rust-app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:9000"
    restart: always
    environment:
      DATABASE_URL: mysql://root:root@db/bluepi
    networks:
      - db-networks

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - db-networks

networks:
  db-networks:

volumes:
  bluepi_db_data:
